language: bash
env:
  global:
    - CC_TAG=10.3
    - TAG=10.3
    - FIXES=ALL
    - REG=sergeipogrebnyak
  matrix:
    - IMAGE=universal-messaging
    - IMAGE=integration-server

stages:
  - infra
  - build
  - deploy

jobs:
  include:
    - stage: infra
      script: 
        - echo "CC ${CC_TAG}"

    - stage: build
      script: echo "$IMAGE"

    - stage: deploy
      script: echo "Deploy $TAG"
