language: bash
env:
  global:
    - CC_TAG=10.3
    - FIXES=ALL
    - REG=sergeipogrebnyak
  matrix:
    # - IMAGE=hello-world TAG=10.3
    - IMAGE=universal-messaging TAG=10.3
    # - IMAGE=universal-messaging TAG=10.1
    - IMAGE=integration-server TAG=10.3
    # - IMAGE=integration-server TAG=10.1
    
script:
  - echo $IMAGE:$TAG
