language: bash
env:
  global:
    - CC_TAG=10.3
    - TAG=10.3
    - FIXES=ALL
    - REG=sergeipogrebnyak
  # matrix:
  #   # - IMAGE=hello-world TAG=10.3
  #   - IMAGE=universal-messaging
  #   # - IMAGE=universal-messaging TAG=10.1
  #   - IMAGE=integration-server
  #   # - IMAGE=integration-server TAG=10.1

stages:
  - builder
  - test
  - deploy

jobs:
  include:
    - stage: builder
      env:
        - IMAGE=none
      script: 
        - echo "CC ${CC_TAG}"

    # test
    - script: echo "universal-messaging"
    - script: echo "integration-server"

    - stage: deploy
      env:
        - IMAGE=none
      script:
        - echo "Deploy $TAG"
