language: bash
env:
  global:
    - CC_TAG=10.3
    - TAG=10.3
    - FIXES=ALL
    - REG=sergeipogrebnyak
  matrix:
    - IMAGE=universal-messaging
    - IMAGE=integration-server

stages:
  - infra
  - test
  - deploy

script: echo $IMAGE

jobs:
  include:
    - stage: infra
      env:
        - IMAGE=none
      script: 
        - echo "CC ${CC_TAG}"

    - stage: deploy
      env:
        - IMAGE=none
      script: echo "Deploy $TAG"
